# PyTorch Fundamentals

In [ ]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+cpu


## Introduction to Tensors

### Creating Tensors

PyTorch tensors created using `torch.Tensor()`

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim # number of dimensions 

0

In [10]:
# vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
# matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
# tensor
tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [16]:
tensor.shape

torch.Size([3, 2, 3])

In [17]:
# Random Tensors
random_tensor = torch.rand(3, 4, 3)
random_tensor

tensor([[[9.1524e-01, 5.9485e-01, 3.1589e-01],
         [4.0847e-01, 7.9849e-01, 8.3978e-01],
         [1.6529e-01, 4.0227e-01, 3.8803e-01],
         [7.2241e-01, 8.9723e-02, 4.0683e-02]],

        [[6.3009e-03, 6.1541e-01, 5.9384e-01],
         [5.5172e-01, 6.7011e-01, 3.2295e-01],
         [6.4534e-02, 5.5973e-01, 3.8651e-01],
         [9.4169e-01, 2.7946e-01, 1.1747e-01]],

        [[7.9712e-01, 3.8752e-02, 6.4768e-01],
         [1.4213e-01, 9.2304e-04, 5.4011e-01],
         [4.3748e-01, 4.3892e-01, 4.2915e-01],
         [2.0006e-01, 6.4774e-01, 9.3024e-01]]])

### PyTorch Datatypes

float 32, float 16 tensors and more

#### Common Errors
- dataset type does not match
- tensors not the right shape
- datasets assigned to different devices

In [ ]:
float_32_tensor = torch.tensor([3., 4., 3.], 
                            dtype=torch.float32,     # Sets the floating point precision
                            device=None,             # Sets which device the tensor gets assigned to
                            require_grad=False)     # whether or not to track gradients with this tensor

float_16_tensor = torch.tensor([3., 4., 3.], dtype=torch.float16)

TypeError: rand() received an invalid combination of arguments - got (float, float, float, device=NoneType, dtype=torch.dtype, require_grad=bool), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, torch.Generator generator, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
