# PyTorch Fundamentals

In [ ]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+cpu


## Introduction to Tensors

### Creating Tensors

PyTorch tensors created using `torch.Tensor()`

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim # number of dimensions 

0

In [10]:
# vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
# matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
# tensor
tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [16]:
tensor.shape

torch.Size([3, 2, 3])

In [17]:
# Random Tensors
random_tensor = torch.rand(3, 4, 3)
random_tensor

tensor([[[9.1524e-01, 5.9485e-01, 3.1589e-01],
         [4.0847e-01, 7.9849e-01, 8.3978e-01],
         [1.6529e-01, 4.0227e-01, 3.8803e-01],
         [7.2241e-01, 8.9723e-02, 4.0683e-02]],

        [[6.3009e-03, 6.1541e-01, 5.9384e-01],
         [5.5172e-01, 6.7011e-01, 3.2295e-01],
         [6.4534e-02, 5.5973e-01, 3.8651e-01],
         [9.4169e-01, 2.7946e-01, 1.1747e-01]],

        [[7.9712e-01, 3.8752e-02, 6.4768e-01],
         [1.4213e-01, 9.2304e-04, 5.4011e-01],
         [4.3748e-01, 4.3892e-01, 4.2915e-01],
         [2.0006e-01, 6.4774e-01, 9.3024e-01]]])

### PyTorch Datatypes

float 32, float 16 tensors and more

#### Common Errors
- dataset type does not match
- tensors not the right shape
- datasets assigned to different devices

In [22]:
float_32_tensor = torch.tensor([3., 4., 3.], 
                            dtype=torch.float32,     # Sets the floating point precision
                            device=None,             # Sets which device the tensor gets assigned to
                            requires_grad=False)     # whether or not to track gradients with this tensor

float_16_tensor = torch.tensor([3., 4., 3.], dtype=torch.float16)

float_32_tensor * float_16_tensor

tensor([ 9., 16.,  9.])

To fix earlier said errors, we have the following codes:
- If not same datatypes, `tensor.dtype`
- If not same shape, `tensor.shape`
- If not the same device, `tensor.device`

#### PyTorch Tensors and Numpy

- NumPy -> PyTorch : `torch.from_numpy(ndarray)`
- PyTorch -> NumPy : `torch.Tensor.numpy()`

**Warning**  
NumPy default datatype -> float64,  
PyTorch default datatype -> float32

##### Reproducibility

We use seed generators for the ran num to make it more reproducible  
  
We need to keep in mind that `torch.manual_seed(random_seed)` only works for a single line of code, so it must be repeated.

In [25]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))